 version: "3.7"

 services:
   app:
     image: cjlapao/ms-graph-collector
     ports:
       - 10000:10000
     environment:
      MONGODB_CONNECTION_STRING: "mongodb://mongodb.local-cluster.internal:27017/?readPreference=primaryPreferred&appname=MongoDB%20Compass&directConnection=true&ssl=false"
      MONGODB_DATABASENAME: "saas_demo"
      HTTP_PORT: 10000
      API_PREFIX: "/api"
