package msgraph_entities

type User struct {
	ID                              string                 `json:"id"`
	DeletedDateTime                 string                 `json:"deletedDateTime"`
	AccountEnabled                  bool                   `json:"accountEnabled"`
	AgeGroup                        string                 `json:"ageGroup"`
	BusinessPhones                  []string               `json:"businessPhones"`
	City                            string                 `json:"city"`
	CreatedDateTime                 string                 `json:"createdDateTime"`
	CreationType                    string                 `json:"creationType"`
	CompanyName                     string                 `json:"companyName"`
	ConsentProvidedForMinor         interface{}            `json:"consentProvidedForMinor"`
	Country                         string                 `json:"country"`
	Department                      string                 `json:"department"`
	DisplayName                     string                 `json:"displayName"`
	EmployeeID                      string                 `json:"employeeId"`
	EmployeeHireDate                interface{}            `json:"employeeHireDate"`
	EmployeeType                    interface{}            `json:"employeeType"`
	FaxNumber                       interface{}            `json:"faxNumber"`
	GivenName                       string                 `json:"givenName"`
	IMAddresses                     []string               `json:"imAddresses"`
	InfoCatalogs                    []interface{}          `json:"infoCatalogs"`
	IsManagementRestricted          interface{}            `json:"isManagementRestricted"`
	IsResourceAccount               interface{}            `json:"isResourceAccount"`
	JobTitle                        string                 `json:"jobTitle"`
	LegalAgeGroupClassification     interface{}            `json:"legalAgeGroupClassification"`
	Mail                            string                 `json:"mail"`
	MailNickname                    string                 `json:"mailNickname"`
	MobilePhone                     string                 `json:"mobilePhone"`
	OnPremisesDistinguishedName     string                 `json:"onPremisesDistinguishedName"`
	OfficeLocation                  string                 `json:"officeLocation"`
	OnPremisesDomainName            string                 `json:"onPremisesDomainName"`
	OnPremisesImmutableID           string                 `json:"onPremisesImmutableId"`
	OnPremisesLastSyncDateTime      string                 `json:"onPremisesLastSyncDateTime"`
	OnPremisesSecurityIdentifier    string                 `json:"onPremisesSecurityIdentifier"`
	OnPremisesSamAccountName        string                 `json:"onPremisesSamAccountName"`
	OnPremisesSyncEnabled           bool                   `json:"onPremisesSyncEnabled"`
	OnPremisesUserPrincipalName     string                 `json:"onPremisesUserPrincipalName"`
	OtherMails                      []interface{}          `json:"otherMails"`
	PasswordPolicies                string                 `json:"passwordPolicies"`
	PostalCode                      string                 `json:"postalCode"`
	PreferredDataLocation           interface{}            `json:"preferredDataLocation"`
	PreferredLanguage               string                 `json:"preferredLanguage"`
	ProxyAddresses                  []string               `json:"proxyAddresses"`
	RefreshTokensValidFromDateTime  string                 `json:"refreshTokensValidFromDateTime"`
	ShowInAddressList               interface{}            `json:"showInAddressList"`
	SignInSessionsValidFromDateTime string                 `json:"signInSessionsValidFromDateTime"`
	State                           string                 `json:"state"`
	StreetAddress                   string                 `json:"streetAddress"`
	Surname                         string                 `json:"surname"`
	UsageLocation                   string                 `json:"usageLocation"`
	UserPrincipalName               string                 `json:"userPrincipalName"`
	ExternalUserState               interface{}            `json:"externalUserState"`
	ExternalUserStateChangeDateTime interface{}            `json:"externalUserStateChangeDateTime"`
	UserType                        string                 `json:"userType"`
	EmployeeOrgData                 interface{}            `json:"employeeOrgData"`
	PasswordProfile                 interface{}            `json:"passwordProfile"`
	AssignedLicenses                []AssignedLicense      `json:"assignedLicenses"`
	AssignedPlans                   []AssignedPlan         `json:"assignedPlans"`
	DeviceKeys                      []interface{}          `json:"deviceKeys"`
	Identities                      []Identity             `json:"identities"`
	OnPremisesExtensionAttributes   map[string]interface{} `json:"onPremisesExtensionAttributes"`
	OnPremisesProvisioningErrors    []interface{}          `json:"onPremisesProvisioningErrors"`
	ProvisionedPlans                []ProvisionedPlan      `json:"provisionedPlans"`
}
